booking/urls.py
from django.urls import path, include
from booking import views 

app_name = "booking"

urlpatterns = [
    path("check_room_availability/", views.check_room_availability, name="check_room_availability"),
    path("delete_session/", views.delete_session, name="delete_session"),
    path("booking_data/<slug:slug>/", views.booking_data, name="booking_data"),

    # Ajax
    path("add_to_selection/", views.add_to_selection, name="add_to_selection"),
    path("delete_selection/", views.delete_selection, name="delete_selection"),
    
    
    path("api/booking/", include("booking.urls_api")),
    
]

hms_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from hotel.admin import StatisticAdminView
from hotel.admin import admin_site
schema_view = get_schema_view(
    openapi.Info(
        title="Hotel Management API",
        default_version='v1',
        description="API documentation for Hotel Management System",
        terms_of_service="https://www.example.com/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('admin/', admin_site.urls),
    #Userauths URLS
    path("user/", include("userauths.urls")),
    
    path("", include("hotel.urls")),
    path("receptionist/", include("receptionist.urls")),

    path("booking/", include("booking.urls")),
    #Ckeditor
    path("ckeditor5/", include("django_ckeditor_5.urls")),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    #API document
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

hotel/urls.py
from django.urls import path,include
from django.contrib import admin
from .admin import admin_site, StatisticAdminView
from hotel import views

app_name = "hotel"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<slug>/", views.hotel_detail, name="hotel_detail"),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>/", views.room_type_detail, name="room_type_detail"),
    #path('admin/', admin.site.urls),
    path('statistics/', StatisticAdminView.as_view(), name='statistics'),

    path("selected_rooms/", views.selected_rooms, name="selected_rooms"),
    # path("checkout/<booking_id>",views.checkout, name="checkout"),
    
    #Payment routes
    path('api/checkout-session/<booking_id>/', views.create_checkout_session, name='api_checkout_session'),
    path('success/<booking_id>/', views.payment_success, name='success'),
    path('failed/<booking_id>/', views.payment_failed, name='failed'),
    
    # API routes
    path('api/', include('hotel.urls_api')), 

]

hotel/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.utils import timezone
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.urls import reverse
from hotel.models import Hotel, Booking, ActivityLog, StaffOnDuty, Room, RoomType, Coupon, Notification
from django.shortcuts import get_object_or_404, redirect, render
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from datetime import datetime
import stripe
from decimal import Decimal
#Trả về danh sách khách sạn có trạng thái live
def index(request):
    hotels = Hotel.objects.filter(status='Live')
    context = {
        'hotels': hotels,
    }
    return render(request, "hotel/hotel.html", context)

#Chi tiết khách sạn theo slug
def hotel_detail(request, slug):
    hotel = Hotel.objects.get(status='Live', slug=slug)
    context = {
        'hotel': hotel,
    }
    return render(request, 'hotel/hotel_detail.html', context)

#Thông tin chi tiết 1 loại phòng
def room_type_detail(request, slug, rt_slug):#king>luxury>eco>basic
    hotel = Hotel.objects.get(status='Live', slug=slug)
    room_type = RoomType.objects.get(hotel=hotel, slug=rt_slug)
    rooms = Room.objects.filter(room_type=room_type, is_available=True)
    
    checkin = request.GET.get('checkin')
    checkout = request.GET.get('checkout')
    adult = request.GET.get('adult')
    children = request.GET.get('children')

    # id = request.GET.get("hotel-id")
    # print("ID=======afaf",id)

    context={
        'hotel': hotel,
        'room_type' : room_type,
        'rooms' : rooms,
        'checkin': checkin,
        'checkout': checkout,
        'adult': adult,
        'children': children,
    }
    
    return render(request, 'hotel/room_type_detail.html', context)

def selected_rooms(request):
    # request.session.pop('selection_data_obj', None)

    total = 0
    room_count = 0
    total_days = 0
    adult = 0 
    children = 0 
    checkin = "0" 
    checkout = "" 
     
    
    if 'selection_data_obj' in request.session:

        if request.method == "POST":
            for h_id, item in request.session['selection_data_obj'].items():
                
                id = int(item['hotel_id'])
                hotel_id = int(item['hotel_id'])

                checkin = item["checkin"]
                checkout = item["checkout"]
                adult = int(item["adult"])
                children = int(item["children"])
                room_type_ = item["room_type"]
                room_id = int(item["room_id"])
                
                user = request.user
                hotel = Hotel.objects.get(id=id)
                room = Room.objects.get(id=room_id)
                room_type = RoomType.objects.get(id=room_type_)

                

                
            date_format = "%Y-%m-%d"
            checkin_date = datetime.strptime(checkin, date_format)
            checout_date = datetime.strptime(checkout, date_format)
            time_difference = checout_date - checkin_date
            total_days = time_difference.days

            full_name = request.POST.get("full_name")
            email = request.POST.get("email")
            phone = request.POST.get("phone")

            booking = Booking.objects.create(
                hotel=hotel,
                room_type=room_type,
                check_in_date=checkin,
                check_out_date=checkout,
                total_days=total_days,
                num_adults=adult,
                num_children=children,
                full_name=full_name,
                email=email,
                phone=phone
                #user=request.user or None
            )

            if request.user.is_authenticated:
                booking.user = request.user
                booking.save()
            else:
                booking.user = None
                booking.save()


            for h_id, item in request.session['selection_data_obj'].items():
                room_id = int(item["room_id"])
                room = Room.objects.get(id=room_id)
                booking.room.add(room)

                room_count += 1
                days = booking.total_days
                price = booking.room_type.price

                room_price = price * room_count
                total = room_price * days

                # print("room_price ==",room_price)
                # print("total ==",total)
            
            booking.total += float(total)
            booking.before_discount += float(total)
            booking.save()

            #messages.success(request, "Checkout Now!")
            return redirect("hotel:checkout", booking.booking_id)

        hotel = None

        for h_id, item in request.session['selection_data_obj'].items():
                
            id = int(item['hotel_id'])
            hotel_id = int(item['hotel_id'])

            checkin = item["checkin"]
            checkout = item["checkout"]
            adult = int(item["adult"])
            children = int(item["children"])
            room_type_ = item["room_type"]
            room_id = int(item["room_id"])
            
            room_type = RoomType.objects.get(id=room_type_)

            date_format = "%Y-%m-%d"
            checkin_date = datetime.strptime(checkin, date_format)
            checout_date = datetime.strptime(checkout, date_format)
            time_difference = checout_date - checkin_date
            total_days = time_difference.days

            room_count += 1
            days = total_days
            price = room_type.price

            room_price = price * room_count
            total = room_price * days
            
            hotel = Hotel.objects.get(id=id)
        print("price== ", price)
        print("room_count===",room_count)
        print("hotel ===", hotel)
        context = {
            "data":request.session['selection_data_obj'], 
            "total_selected_items": len(request.session['selection_data_obj']),
            "total":total,
            "total_days":total_days,
            "adult":adult,
            "children":children,   
            "checkin":checkin,   
            "checkout":checkout,   
            "hotel":hotel,   
        }

        return render(request, "hotel/selected_rooms.html", context)
        #return render(request, "hotel/selected_rooms.html")
    else:
        messages.warning(request, "You don't have any room selections yet!")
        return redirect("/")

def checkout(request,booking_id):
    booking = Booking.objects.get(booking_id=booking_id)
    if request.method == "POST":
        code = request.POST.get("code")
        print("code====",code)
        try:
            coupon = Coupon.objects.get(code=code, active=True)
            #print("Coupon",coupon)
            if coupon in booking.coupons.all():
                messages.warning(request, "Coupon already activated")
                return redirect("hotel:checkout", booking.booking_id)
            else:
                if coupon.type == "Percentage":
                    discount = booking.total * coupon.discount /100
                else:
                    discount = coupon.discount
                booking.coupons.add(coupon)
                booking.total-=discount
                booking.saved+=discount
                booking.save()
                
                messages.success(request, "Coupon activated")
                return redirect("hotel:checkout", booking.booking_id)
        except:
            messages.error(request, "Coupon does not exists")
            return redirect("hotel:checkout", booking.booking_id)
    context={
        "booking":booking,
        "stripe_publishable_key": settings.STRIPE_PUBLIC_KEY,
    }

    return render(request, "hotel/checkout.html", context)


@csrf_exempt
def create_checkout_session(request, booking_id):
    booking = Booking.objects.get(booking_id=booking_id)
    stripe.api_key = settings.STRIPE_SECRET_KEY

    checkout_session = stripe.checkout.Session.create(
        customer_email = booking.email,
        payment_method_types=['card'],
        line_items=[
            {
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                    'name': booking.full_name,
                    },
                    'unit_amount': int(booking.total * 100),
                },
                'quantity': 1,
            }
        ],
        mode='payment',
        success_url=request.build_absolute_uri(reverse('hotel:success', args=[booking.booking_id])) + "?session_id={CHECKOUT_SESSION_ID}&success_id="+booking.success_id+'&booking_total='+str(booking.total),
        cancel_url=request.build_absolute_uri(reverse('hotel:failed', args=[booking.booking_id]))+ "?session_id={CHECKOUT_SESSION_ID}",
    )
    booking.payment_status = "processing"
    booking.stripe_payment_intent = checkout_session['id']
    booking.save()

    print("checkout session", checkout_session)
    return JsonResponse({'sessionId': checkout_session.id})


def payment_success(request, booking_id):
    success_id = request.GET.get('success_id')
    booking_total = request.GET.get('booking_total')

    if success_id and booking_total: 
        success_id = success_id.rstrip('/')
        booking_total = booking_total.rstrip('/')
        
        booking = Booking.objects.get(booking_id=booking_id, success_id=success_id)
        
        # Payment Verification
        if booking.total == Decimal(booking_total):
            if booking.payment_status == "processing": #processing #paid
                booking.payment_status = "paid"
                booking.save()

                noti = Notification.objects.create(booking=booking,type="Booking Confirmed",)
                if request.user.is_authenticated:
                    noti.user = request.user
                    noti.save()
                else:

templates/hotel/checkout.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
  
<div id="main_wrapper">
  
  <div id="titlebar" class="gradient">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>All Room Selections</h2>
          <nav id="breadcrumbs">
            <ul>
              <li><a>Home</a></li>
              <li><a>Hotel</a></li>
              <li><a>Rooms</a></li>
              <li>My selected rooms</li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
  
  <div class="container margin-bottom-75">
    <div class="row">
      <div class="col-lg-8 col-md-8 utf_listing_payment_section">
	    <div class="notification warning closeable">
			<p><span>NOTE!</span> Review your order before payment.</p>
			<a class="close" href="#"></a> 
		  </div>
        <div class="utf_booking_listing_section_form margin-bottom-40">
            <h3><i class="fas fa-bed"></i> Selected Rooms</h3>
            <div class="utf_listing_section">
                    <div class="utf_pricing_list_section">
                        <ul>
                            {% for r in booking.room.all %}
                                <li>
                                    <h5>Room: {{r.room_type.type}} </h5>
                                    <p><strong>Beds :</strong> {{r.number_of_beds}}  </p>
                                    <span>${{r.room_type.price}} </span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
            </div>
        </div>
            
        <div class="utf_booking_listing_section_form margin-bottom-40">
		  <h3><i class="fas fa-user"></i> Billing Information</h3>
			<div class="row">
			  <div class="col-md-12">
				<label>First Name</label>
				<input name="full_name" type="text" value="{{booking.full_name}}" readonly placeholder="First Name">
			  </div>
			  <div class="col-md-6">
				<div class="medium-icons">
				  <label>E-Mail</label>
				  <input name="email" id="email" type="text" value="{{booking.email}}" readonly placeholder="Email">
				</div>
			  </div>
			  <div class="col-md-6">
				<div class="medium-icons">
				  <label>Phone</label>
				  <input name="phone" type="text" value="{{booking.phone}}" readonly >
				</div>
			  </div>
              <div class="col-lg-12">
			  </div>
			</div>
		</div>

		
	  </div>
      <div class="col-lg-4 col-md-4 margin-top-0 utf_listing_payment_section">
        <div class="utf_booking_listing_item_container compact utf_order_summary_widget_section">
          <div class="listing-item"> <img src="{{booking.hotel.image.url}}" alt="">
            <div class="utf_listing_item_content">              
              <h3>{{booking.hotel.name}}</h3>
              <span><i class="fa fa-map-marker"></i> The Ritz-Carlton, Hong Kong</span>
						<span><i class="fa fa-phone"></i> (+15) 124-796-3633</span>											
			  <div class="utf_star_rating_section" data-rating="4.5">
				<div class="utf_counter_star_rating">(18) Reviews</div>
			  </div>
			</div>
          </div>
        </div>
        <div class="boxed-widget opening-hours summary margin-top-0">
          <h3><i class="fa fa-calendar-check-o"></i> Booking Summary</h3>
          <ul>
            <li>Check-in <span>{{booking.check_in_date}}</span></li>
			      <li>Check-out <span>{{booking.check_out_date}}</span></li>            
            <li>Adults <span>{{ booking.num_adults }} Adults</span></li>
            <li>Children <span>{{ booking.num_children }} Children</span></li>
			      <li>V.A.T <span>$0.00</span></li>
            
            {% if booking.saved != 0.00 %}
			      <li>Discount<span>-${{booking.saved}}</span></li>
            {% endif %}

            <li class="total-costs">
              <form action="" method="POST">
                {% csrf_token %}
                <div class="col-md-8">
                  <input id="couponCode" name="code" placeholder="Have a coupon enter here..." required="" type="text">
                </div>
                <div class="col-md-4">
                  <input type="submit" class="coupon_code" value="Apply">	
                </div>
              </form>
              <div class="clearfix"></div>
            </li>
            <li class="total-costs">Total Cost <span>${{booking.total}}</span></li>
          </ul>
          <form method="POST" action="https://checkout.flutterwave.com/v3/hosted/pay">
               <input type="hidden" name="public_key" value="FLWPUBK_TEST-a2c377d3cf56b37b9e660f85e26d2f8f-X" />
               <input type="hidden" name="customer[email]" value="{{booking.email}}" />
               <input type="hidden" name="customer[name]" value="{{booking.full_name}}" />
               <input type="hidden" name="tx_ref" value="ID-{{booking.booking_id}}" />
               <input type="hidden" name="amount" value="{{booking.total}}" />
               <input type="hidden" name="currency" value="USD" />
               <input type="hidden" name="meta[token]" value="54" />
               <input type="hidden" name="redirect_url" value="{{website_address}}/success/{{booking.booking_id}}/?success_id={{booking.success_id}}&booking_total={{booking.total}}" />
               
               <button id="flutter-btn" class="button utf_booking_confirmation_button margin-top-20 w-100 " style="background-color: orange; color: rgb(37, 28, 3);">Pay with Flutterwave <img src="https://asset.brandfetch.io/iddYbQIdlK/idmlgmHt_3.png" style="width: 40px;" alt=""></button> 		
          </form>
          <button id="checkout-button" class="button utf_booking_confirmation_button margin-top-10 margin-bottom-10 w-100">Pay with Stripe <i class="fas fa-credit-card"></i></button> 		
          <div id="paypal-button-container"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://js.stripe.com/v3/"></script>
<script>console.log("Publishable key:", '{{ stripe_publishable_key }}');</script>

<script type="text/javascript">

    

    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe('{{ stripe_publishable_key }}');
    var checkoutButton = document.getElementById('checkout-button');

    checkoutButton.addEventListener('click', function () {

        var email = document.getElementById('email').value;
        if (email.length == 0) {
            alert("Please enter your email address.");
            return;
        }

        checkoutButton.innerHTML = "Starting..."
        
        fetch("{% url 'hotel:api_checkout_session' booking_id=booking.booking_id %}", {
            method: 'POST',
            body: JSON.stringify(
                { email: email }
            )
        }).then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.sessionId });
            })
            .then(function (result) {
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error('Error:', error);
            });
    });
</script>


<script>
   booking_id = "{{booking.booking_id}}"
   booking_total = "{{booking.total}}"
   success_id = "{{booking.success_id}}"
   id = "{{booking.id}}"

   paypal.Buttons({

      createOrder: function(data, actions) {
         return actions.order.create({
            purchase_units: [{
               amount: {
                  value: booking_total
               }
            }]
         })
      },

       onApprove: function(data, actions) {
           return actions.order.capture().then(function(Details){
              window.location.href = "/success/"+ booking_id +"/?PayerID="+ id +"&success_id=" + success_id + "&booking_total=" + booking_total + "/" ; 
           })
       }

   }).render('#paypal-button-container');
</script>

<script>
  let flutter_btn = document.getElementById("flutter-btn")
  flutter_btn.addEventListener("click", function(){
    flutter_btn.innerHTML = "Starting..."
  })
</script>
  
{% endblock content %}

templates/hotel/payment_success.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
  
  <div class="not_found_block">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <section id="not-found" class="center">
            <h2 class="margin-bottom-10"><i class="fas fa-check-circle" style="color: green;"></i></h2>
            <p style="margin-top: 10px; color: black;"><b>Checkout & Payment Successfull!</b></p>
            <div class="utf_error_description_part utf_ferror_description">  
                <span class="f-primary animated v fadeInRight">We have sent your booking summary to <b>{{ booking.email }}. Thank you.</b></span> 
            </div>
            <a href="#" class="button margin-top-20">Visit Dashboard</a>
            <a href="#" target="_blank" class="button margin-top-20">View Invoice 🧾</a>
            <div class="row">
              <div class="col-lg-6 col-lg-offset-3">
                <div class="gray-style margin-top-50 margin-bottom-10">
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/hotel/room_type_detail.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
  
  <div id="titlebar" class="gradient">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>{{room_type.type}} Room</h2>
          <nav id="breadcrumbs">
            <ul>
              <li><p>{{rooms.count}} Available Rooms</p></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>

  
  <section class="fullwidth_block margin-top-0 padding-top-0 padding-bottom-50" data-background-color="#fff"> 
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h3 class="headline_part centered margin-bottom-20">All Available Rooms<span>The {{ room_type.type }} room has {{ rooms.count }} available room(s)</span></h3>
        </div>
      </div>
      <div class="row">  
        <div class="col-lg-8 "> 
          
          {% for r in rooms %}
              <div class="plan featured col-md-4 col-sm-6 col-xs-12">
              <div class="utf_price_plan">
                  <h3>Room No. {{ r.room_number }}</h3>
                  <span class="value">${{r.room_type.price}}<span>/Per Night</span></span> 
              </div>
              <div class="utf_price_plan_features">
                  <ul>
                  <li>Beds: {{r.room_type.number_of_beds}} </li>
                  <li>Room Capacity: {{r.room_type.room_capacity}}</li>
                  </ul>
                  <input type="hidden" class="room_id_{{r.id}}" value="{{r.id}}" id="room_id">
                  <input type="hidden" class="room_number_{{r.id}}" value="{{r.room_number}}" id="room_number">
                  <button class="button border add-to-selection" data-index="{{r.id}}"><i class="fas fa-shopping-cart"></i> Add To Selection</button> 
              </div>
              </div>
          {% endfor %}
          <input type="hidden" value="{{hotel.id}}" id="id">
          <input type="hidden" value="{{hotel.name}}" id="hotel_name">
          <input type="hidden" value="{{room_type.type}}" id="room_name">
          <input type="hidden" value="{{room_type.price}}" id="room_price">
          <input type="hidden" value="{{room_type.number_of_beds}}" id="number_of_beds">
          <input type="hidden" value="{{room_type.id}}" id="room_type">
          <input type="hidden" value="{{checkin}}" id="checkin">
          <input type="hidden" value="{{checkout}}" id="checkout">
          <input type="hidden" value="{{adult}}" id="adult">
          <input type="hidden" value="{{children}}" id="children">
 
        </div>  
        <div class="col-lg-4">
            <div class=" booking_widget_box" style="border: 1px dashed rgba(42, 1, 119, 0.61); padding: 14px; border-radius: 10px;">
              <h3><i class="fa fa-calendar"></i> Booking</h3>
              <form class="row with-forms margin-top-0" method="POST" action="{% url 'booking:check_room_availability' %}">
                  {% csrf_token %}
                  <input type="hidden" value="{{hotel.id}}" name="hotel-id" id="">
                  <div class="col-lg-12 col-md-12 select_date_box">
                      <label for="">Check-in Date</label>
                      <input type="date" id="date-picker" value="{{checkin}}" name="checkin" placeholder="Select Date">
                  </div>
                  <div class="col-lg-12 col-md-12 select_date_box">
                      <label for="">Check-out Date</label>
                      <input type="date" class="checkout_date" name="checkout" value="{{checkout}}"  placeholder="Select Date">
                  </div>
                  <div class="with-forms">
                      <div class="col-lg-12 col-md-12">
                          <a href="#">Guests <span class="qtyTotal" name="qtyTotal">1</span></a>
                          <div class="panel-dropdown-content">
                              <div class="qtyButtons">
                                  <div class="qtyTitle">Adults</div>
                                  <input type="text" name="adult" {% if adult == None %}value="1"{% else %}value="{{adult}}"{% endif %}>
                              </div>
                              <div class="qtyButtons">
                                  <div class="qtyTitle">Childrens</div>
                                  <input type="text" name="children" {% if children == None %}value="1"{% else %}value="{{children}}"{% endif %}>
                              </div>
                          </div>
                      </div>
                  </div>

                  <div class="with-forms margin-top-30">
                      <div class="col-lg-12 col-md-12 ">
                          <a href="#">Select Room Type</a>
                          <select name="room-type" class="utf_chosen_select_single" required>
                              <!-- <option value="{{room_type|lower}}">{{room_type}}</option> -->
                              <option value="{{room_type|lower}}">{{room_type}}</option>

                              {% for r in hotel.hotel_room_types %}
                                  <option value="{{r.slug}}">{{r.type}}</option>
                              {% endfor %}
                            </select>
                      </div>
                  </div>
                
                  <button type="submit" class="utf_progress_button button fullwidth_block margin-top-5">Check Availability</button>
              </form>
              <button class="like-button add_to_wishlist"><span class="like-icon"></span> Add to Wishlist</button>
              <div class="clearfix"></div>
            </div>
        </div>      
              
      </div>      
    </div>    
  </section>

  <script>
    $(document).ready(function(){
        
        var dateInput = $('#checkout_date');

        dateInput.on('change', function() {
            var selectedDate = dateInput.val();
            console.log('Selected date:', selectedDate);
        });
    })
  </script>
  
{% endblock content %}